[2021-12-20 10:40:57,658] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kildare.scrap_data scheduled__2021-12-19T09:45:00+00:00 [queued]>
[2021-12-20 10:40:58,892] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kildare.scrap_data scheduled__2021-12-19T09:45:00+00:00 [queued]>
[2021-12-20 10:40:58,900] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 10:40:58,908] {taskinstance.py:1242} INFO - Starting attempt 3 of 4
[2021-12-20 10:40:58,916] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 10:40:59,395] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-19 09:45:00+00:00
[2021-12-20 10:40:59,939] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_kildare', 'scrap_data', 'scheduled__2021-12-19T09:45:00+00:00', '--job-id', '3423', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_kildare.py', '--cfg-path', '/tmp/tmptz7ot_8m', '--error-file', '/tmp/tmp01x_bsjy']
[2021-12-20 10:40:59,974] {standard_task_runner.py:77} INFO - Job 3423: Subtask scrap_data
[2021-12-20 10:40:59,512] {standard_task_runner.py:52} INFO - Started process 4542 to run task
[2021-12-20 10:41:04,307] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_kildare.scrap_data scheduled__2021-12-19T09:45:00+00:00 [running]> on host a35fe600e898
[2021-12-20 10:41:13,003] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_kildare
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T09:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T09:45:00+00:00
[2021-12-20 10:41:14,836] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-20 10:41:14,937] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py kildare
[2021-12-20 11:09:09,604] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2021-12-20 11:09:09,698] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 4542
[2021-12-20 11:09:09,721] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-20 11:09:09,736] {spark_submit.py:644} INFO - Sending kill signal to spark-submit
[2021-12-20 11:09:12,940] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-20 11:09:13,497] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_kildare, task_id=scrap_data, execution_date=20211219T094500, start_date=20211220T104057, end_date=20211220T110913
[2021-12-20 11:09:16,173] {standard_task_runner.py:91} ERROR - Failed to execute job 3423 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-20 11:09:17,554] {process_utils.py:66} INFO - Process psutil.Process(pid=4542, status='terminated', exitcode=1, started='10:40:58') (4542) terminated with exit code 1
[2021-12-20 11:09:17,594] {process_utils.py:66} INFO - Process psutil.Process(pid=4570, status='terminated', started='10:41:15') (4570) terminated with exit code None
