[2021-12-14 04:49:43,248] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_mayo.scrap_data scheduled__2021-12-13T04:00:00+00:00 [queued]>
[2021-12-14 04:49:47,361] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_mayo.scrap_data scheduled__2021-12-13T04:00:00+00:00 [queued]>
[2021-12-14 04:49:47,420] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 04:49:47,550] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-14 04:49:47,656] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 04:49:50,051] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-13 04:00:00+00:00
[2021-12-14 04:49:51,959] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_mayo', 'scrap_data', 'scheduled__2021-12-13T04:00:00+00:00', '--job-id', '2093', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_mayo.py', '--cfg-path', '/tmp/tmpy_e52jok', '--error-file', '/tmp/tmpxl027sfp']
[2021-12-14 04:49:52,132] {standard_task_runner.py:77} INFO - Job 2093: Subtask scrap_data
[2021-12-14 04:49:50,556] {standard_task_runner.py:52} INFO - Started process 33469 to run task
[2021-12-14 04:50:01,663] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_mayo.scrap_data scheduled__2021-12-13T04:00:00+00:00 [running]> on host c81f81825bc0
[2021-12-14 04:50:09,372] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_mayo
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-13T04:00:00+00:00
[2021-12-14 04:50:10,578] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-14 04:50:10,813] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py mayo
[2021-12-14 04:51:00,928] {base_job.py:230} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 202, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2171, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2244, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-12-14 07:06:11,498] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-14 07:07:14,029] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-14 07:07:14,037] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-14 07:07:14,042] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-14 07:07:14,045] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-14 07:07:14,049] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-14 07:10:23,701] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-14 07:10:25,594] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-14 07:10:25,717] {spark_submit.py:514} INFO - deployMode              null
[2021-12-14 07:10:26,022] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-14 07:10:26,150] {spark_submit.py:514} INFO - executorCores           null
[2021-12-14 07:10:26,343] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-14 07:10:26,599] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-14 07:10:27,252] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-14 07:10:27,336] {spark_submit.py:514} INFO - driverCores             null
[2021-12-14 07:10:27,381] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-14 07:10:27,434] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-14 07:10:27,497] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-14 07:10:27,592] {spark_submit.py:514} INFO - supervise               false
[2021-12-14 07:10:27,886] {spark_submit.py:514} INFO - queue                   null
[2021-12-14 07:10:27,906] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-14 07:10:27,956] {spark_submit.py:514} INFO - files                   null
[2021-12-14 07:10:28,031] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-14 07:10:28,461] {spark_submit.py:514} INFO - archives                null
[2021-12-14 07:10:28,723] {spark_submit.py:514} INFO - mainClass               null
[2021-12-14 07:10:29,113] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-14 07:10:29,203] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-14 07:10:29,394] {spark_submit.py:514} INFO - childArgs               [mayo]
[2021-12-14 07:10:29,873] {spark_submit.py:514} INFO - jars                    null
[2021-12-14 07:10:30,185] {spark_submit.py:514} INFO - packages                null
[2021-12-14 07:10:30,276] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-14 07:10:30,371] {spark_submit.py:514} INFO - repositories            null
[2021-12-14 07:10:30,500] {spark_submit.py:514} INFO - verbose                 true
[2021-12-14 07:10:31,409] {spark_submit.py:514} INFO - 
[2021-12-14 07:10:31,489] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-14 07:10:31,554] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-14 07:10:31,700] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-14 07:10:31,740] {spark_submit.py:514} INFO - 
[2021-12-14 07:10:31,756] {spark_submit.py:514} INFO - 
