[2021-12-28 11:02:54,540] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [queued]>
[2021-12-28 11:02:54,684] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [queued]>
[2021-12-28 11:02:54,709] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 11:02:54,719] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-28 11:02:54,726] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 11:02:54,860] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-27 09:55:00+00:00
[2021-12-28 11:02:54,985] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_laois', 'scrap_data', 'scheduled__2021-12-27T09:55:00+00:00', '--job-id', '5004', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_laois.py', '--cfg-path', '/tmp/tmppas6qa7y', '--error-file', '/tmp/tmpnc2lr7n8']
[2021-12-28 11:02:54,997] {standard_task_runner.py:77} INFO - Job 5004: Subtask scrap_data
[2021-12-28 11:02:54,898] {standard_task_runner.py:52} INFO - Started process 43176 to run task
[2021-12-28 11:02:55,685] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 11:02:56,570] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_laois
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T09:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T09:55:00+00:00
[2021-12-28 11:02:56,690] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 11:02:56,706] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois
[2021-12-28 13:28:05,758] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2021-12-28 13:28:09,191] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 43176
[2021-12-28 13:28:09,294] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-28 13:28:09,539] {process_utils.py:66} INFO - Process psutil.Process(pid=43254, status='terminated', started='11:02:57') (43254) terminated with exit code None
[2021-12-28 13:28:09,583] {process_utils.py:66} INFO - Process psutil.Process(pid=43199, status='terminated', started='11:02:56') (43199) terminated with exit code None
[2021-12-28 13:28:10,374] {process_utils.py:66} INFO - Process psutil.Process(pid=43255, status='terminated', started='11:02:57') (43255) terminated with exit code None
[2021-12-28 13:28:10,523] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-28 13:28:10,940] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_laois, task_id=scrap_data, execution_date=20211227T095500, start_date=20211228T110254, end_date=20211228T132810
[2021-12-28 13:28:12,337] {standard_task_runner.py:91} ERROR - Failed to execute job 5004 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-28 13:28:13,440] {process_utils.py:66} INFO - Process psutil.Process(pid=43176, status='terminated', exitcode=1, started='11:02:54') (43176) terminated with exit code 1
