[2021-12-08 02:15:02,654] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kildare.scrap_data scheduled__2021-12-07T02:15:00+00:00 [queued]>
[2021-12-08 02:15:02,689] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kildare.scrap_data scheduled__2021-12-07T02:15:00+00:00 [queued]>
[2021-12-08 02:15:02,692] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 02:15:02,693] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 02:15:02,694] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 02:15:02,714] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-07 02:15:00+00:00
[2021-12-08 02:15:02,725] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_kildare', 'scrap_data', 'scheduled__2021-12-07T02:15:00+00:00', '--job-id', '596', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_kildare.py', '--cfg-path', '/tmp/tmptb7c_azh', '--error-file', '/tmp/tmpef7rhve4']
[2021-12-08 02:15:02,726] {standard_task_runner.py:77} INFO - Job 596: Subtask scrap_data
[2021-12-08 02:15:02,721] {standard_task_runner.py:52} INFO - Started process 28520 to run task
[2021-12-08 02:15:02,825] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_kildare.scrap_data scheduled__2021-12-07T02:15:00+00:00 [running]> on host 041e6f8654c3
[2021-12-08 02:15:02,987] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_kildare
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-07T02:15:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-07T02:15:00+00:00
[2021-12-08 02:15:03,020] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-08 02:15:03,025] {spark_submit.py:362} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py kildare
[2021-12-08 02:15:05,599] {spark_submit.py:523} INFO - Using properties file: null
[2021-12-08 02:15:05,743] {spark_submit.py:523} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-08 02:15:05,746] {spark_submit.py:523} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-08 02:15:05,747] {spark_submit.py:523} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-08 02:15:05,748] {spark_submit.py:523} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-08 02:15:05,749] {spark_submit.py:523} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-08 02:15:05,819] {spark_submit.py:523} INFO - Parsed arguments:
[2021-12-08 02:15:05,822] {spark_submit.py:523} INFO - master                  spark://spark:7077
[2021-12-08 02:15:05,824] {spark_submit.py:523} INFO - deployMode              null
[2021-12-08 02:15:05,826] {spark_submit.py:523} INFO - executorMemory          null
[2021-12-08 02:15:05,827] {spark_submit.py:523} INFO - executorCores           null
[2021-12-08 02:15:05,828] {spark_submit.py:523} INFO - totalExecutorCores      null
[2021-12-08 02:15:05,830] {spark_submit.py:523} INFO - propertiesFile          null
[2021-12-08 02:15:05,831] {spark_submit.py:523} INFO - driverMemory            null
[2021-12-08 02:15:05,832] {spark_submit.py:523} INFO - driverCores             null
[2021-12-08 02:15:05,833] {spark_submit.py:523} INFO - driverExtraClassPath    null
[2021-12-08 02:15:05,834] {spark_submit.py:523} INFO - driverExtraLibraryPath  null
[2021-12-08 02:15:05,837] {spark_submit.py:523} INFO - driverExtraJavaOptions  null
[2021-12-08 02:15:05,841] {spark_submit.py:523} INFO - supervise               false
[2021-12-08 02:15:05,844] {spark_submit.py:523} INFO - queue                   null
[2021-12-08 02:15:05,845] {spark_submit.py:523} INFO - numExecutors            null
[2021-12-08 02:15:05,847] {spark_submit.py:523} INFO - files                   null
[2021-12-08 02:15:05,848] {spark_submit.py:523} INFO - pyFiles                 null
[2021-12-08 02:15:05,852] {spark_submit.py:523} INFO - archives                null
[2021-12-08 02:15:05,853] {spark_submit.py:523} INFO - mainClass               null
[2021-12-08 02:15:05,854] {spark_submit.py:523} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-08 02:15:05,855] {spark_submit.py:523} INFO - name                    scrap data
[2021-12-08 02:15:05,855] {spark_submit.py:523} INFO - childArgs               [kildare]
[2021-12-08 02:15:05,856] {spark_submit.py:523} INFO - jars                    null
[2021-12-08 02:15:05,857] {spark_submit.py:523} INFO - packages                null
[2021-12-08 02:15:05,858] {spark_submit.py:523} INFO - packagesExclusions      null
[2021-12-08 02:15:05,859] {spark_submit.py:523} INFO - repositories            null
[2021-12-08 02:15:05,860] {spark_submit.py:523} INFO - verbose                 true
[2021-12-08 02:15:05,862] {spark_submit.py:523} INFO - 
[2021-12-08 02:15:05,863] {spark_submit.py:523} INFO - Spark properties used, including those specified through
[2021-12-08 02:15:05,864] {spark_submit.py:523} INFO - --conf and those from the properties file null:
[2021-12-08 02:15:05,865] {spark_submit.py:523} INFO - (spark.master,spark://spark:7077)
[2021-12-08 02:15:05,867] {spark_submit.py:523} INFO - 
[2021-12-08 02:15:05,867] {spark_submit.py:523} INFO - 
[2021-12-08 02:15:06,290] {spark_submit.py:523} INFO - Main class:
[2021-12-08 02:15:06,320] {spark_submit.py:523} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-08 02:15:06,321] {spark_submit.py:523} INFO - Arguments:
[2021-12-08 02:15:06,323] {spark_submit.py:523} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-08 02:15:06,324] {spark_submit.py:523} INFO - null
[2021-12-08 02:15:06,326] {spark_submit.py:523} INFO - kildare
[2021-12-08 02:15:06,327] {spark_submit.py:523} INFO - --verbose
[2021-12-08 02:15:06,328] {spark_submit.py:523} INFO - Spark config:
[2021-12-08 02:15:06,330] {spark_submit.py:523} INFO - (spark.app.name,scrap data)
[2021-12-08 02:15:06,331] {spark_submit.py:523} INFO - (spark.master,spark://spark:7077)
[2021-12-08 02:15:06,332] {spark_submit.py:523} INFO - (spark.submit.pyFiles,)
[2021-12-08 02:15:06,334] {spark_submit.py:523} INFO - (spark.submit.deployMode,client)
[2021-12-08 02:15:06,335] {spark_submit.py:523} INFO - Classpath elements:
[2021-12-08 02:15:06,336] {spark_submit.py:523} INFO - 
[2021-12-08 02:15:06,337] {spark_submit.py:523} INFO - 
[2021-12-08 02:15:06,339] {spark_submit.py:523} INFO - 
[2021-12-08 02:15:07,703] {spark_submit.py:523} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-08 02:15:07,719] {spark_submit.py:523} INFO - 21/12/08 02:15:07 INFO SparkContext: Running Spark version 3.2.0
[2021-12-08 02:15:07,859] {spark_submit.py:523} INFO - 21/12/08 02:15:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-08 02:15:08,186] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO ResourceUtils: ==============================================================
[2021-12-08 02:15:08,187] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-08 02:15:08,190] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO ResourceUtils: ==============================================================
[2021-12-08 02:15:08,193] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-08 02:15:08,290] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-08 02:15:08,320] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO ResourceProfile: Limiting resource is cpu
[2021-12-08 02:15:08,321] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-08 02:15:08,549] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO SecurityManager: Changing view acls to: ***
[2021-12-08 02:15:08,551] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO SecurityManager: Changing modify acls to: ***
[2021-12-08 02:15:08,553] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO SecurityManager: Changing view acls groups to:
[2021-12-08 02:15:08,554] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO SecurityManager: Changing modify acls groups to:
[2021-12-08 02:15:08,557] {spark_submit.py:523} INFO - 21/12/08 02:15:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-08 02:15:09,161] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO Utils: Successfully started service 'sparkDriver' on port 46139.
[2021-12-08 02:15:09,221] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO SparkEnv: Registering MapOutputTracker
[2021-12-08 02:15:09,319] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-08 02:15:09,393] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-08 02:15:09,399] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-08 02:15:09,420] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-08 02:15:09,492] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-fdd31dc6-0a6a-4289-a54a-1c71ed717703
[2021-12-08 02:15:09,544] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-08 02:15:09,590] {spark_submit.py:523} INFO - 21/12/08 02:15:09 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-08 02:15:10,132] {spark_submit.py:523} INFO - 21/12/08 02:15:10 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2021-12-08 02:15:10,306] {spark_submit.py:523} INFO - 21/12/08 02:15:10 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://041e6f8654c3:4040
[2021-12-08 02:15:10,977] {spark_submit.py:523} INFO - 21/12/08 02:15:10 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-08 02:15:11,142] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO TransportClientFactory: Successfully created connection to spark/172.31.0.4:7077 after 72 ms (0 ms spent in bootstraps)
[2021-12-08 02:15:11,431] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20211208021511-0082
[2021-12-08 02:15:11,437] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20211208021511-0082/0 on worker-20211207194546-172.31.0.5-40317 (172.31.0.5:40317) with 6 core(s)
[2021-12-08 02:15:11,443] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO StandaloneSchedulerBackend: Granted executor ID app-20211208021511-0082/0 on hostPort 172.31.0.5:40317 with 6 core(s), 1024.0 MiB RAM
[2021-12-08 02:15:11,449] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20211208021511-0082/1 on worker-20211207194546-172.31.0.6-46445 (172.31.0.6:46445) with 6 core(s)
[2021-12-08 02:15:11,451] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO StandaloneSchedulerBackend: Granted executor ID app-20211208021511-0082/1 on hostPort 172.31.0.6:46445 with 6 core(s), 1024.0 MiB RAM
[2021-12-08 02:15:11,494] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42309.
[2021-12-08 02:15:11,506] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO NettyBlockTransferService: Server created on 041e6f8654c3:42309
[2021-12-08 02:15:11,511] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-08 02:15:11,594] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 041e6f8654c3, 42309, None)
[2021-12-08 02:15:11,693] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO BlockManagerMasterEndpoint: Registering block manager 041e6f8654c3:42309 with 434.4 MiB RAM, BlockManagerId(driver, 041e6f8654c3, 42309, None)
[2021-12-08 02:15:11,709] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 041e6f8654c3, 42309, None)
[2021-12-08 02:15:11,712] {spark_submit.py:523} INFO - 21/12/08 02:15:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 041e6f8654c3, 42309, None)
[2021-12-08 02:15:12,267] {spark_submit.py:523} INFO - 21/12/08 02:15:12 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2021-12-08 02:15:12,362] {spark_submit.py:523} INFO - /home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py:238: FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2021-12-08 02:15:12,365] {spark_submit.py:523} INFO - FutureWarning
[2021-12-08 02:15:12,716] {spark_submit.py:523} INFO - 21/12/08 02:15:12 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20211208021511-0082/0 is now RUNNING
[2021-12-08 02:15:12,872] {spark_submit.py:523} INFO - 21/12/08 02:15:12 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20211208021511-0082/1 is now RUNNING
[2021-12-08 02:15:12,948] {spark_submit.py:523} INFO - 21/12/08 02:15:12 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2021-12-08 02:15:13,066] {spark_submit.py:523} INFO - 21/12/08 02:15:13 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2021-12-08 02:15:28,828] {spark_submit.py:523} INFO - running...
[2021-12-08 02:15:31,293] {spark_submit.py:523} INFO - running...
[2021-12-08 02:15:39,821] {spark_submit.py:523} INFO - running...
[2021-12-08 02:15:43,385] {spark_submit.py:523} INFO - running...
[2021-12-08 02:15:49,083] {spark_submit.py:523} INFO - running...
[2021-12-08 02:15:53,726] {spark_submit.py:523} INFO - 21/12/08 02:15:53 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.31.0.5:50216) with ID 0,  ResourceProfileId 0
[2021-12-08 02:15:54,115] {spark_submit.py:523} INFO - running...
[2021-12-08 02:15:55,627] {spark_submit.py:523} INFO - 21/12/08 02:15:55 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.31.0.6:44988) with ID 1,  ResourceProfileId 0
[2021-12-08 02:15:59,880] {spark_submit.py:523} INFO - running...
[2021-12-08 02:16:00,513] {spark_submit.py:523} INFO - 21/12/08 02:16:00 INFO BlockManagerMasterEndpoint: Registering block manager 172.31.0.5:45177 with 366.3 MiB RAM, BlockManagerId(0, 172.31.0.5, 45177, None)
[2021-12-08 02:16:02,606] {spark_submit.py:523} INFO - 21/12/08 02:16:02 INFO BlockManagerMasterEndpoint: Registering block manager 172.31.0.6:36917 with 366.3 MiB RAM, BlockManagerId(1, 172.31.0.6, 36917, None)
[2021-12-08 02:16:05,229] {spark_submit.py:523} INFO - running...
[2021-12-08 02:16:13,125] {spark_submit.py:523} INFO - running...
[2021-12-08 02:16:16,526] {spark_submit.py:523} INFO - running...
[2021-12-08 02:16:24,629] {spark_submit.py:523} INFO - running...
[2021-12-08 02:16:35,649] {spark_submit.py:523} INFO - running...
[2021-12-08 02:16:39,534] {spark_submit.py:523} INFO - IncompleteRead(78590 bytes read, 110629 more expected)
[2021-12-08 02:16:39,667] {spark_submit.py:523} INFO - Traceback (most recent call last):
[2021-12-08 02:16:39,765] {spark_submit.py:523} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 17, in <module>
[2021-12-08 02:16:39,790] {spark_submit.py:523} INFO - get_rent_parse_county_json(county)
[2021-12-08 02:16:39,816] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/fptools/fptools.py", line 191, in h
[2021-12-08 02:16:40,031] {spark_submit.py:523} INFO - return g(x, f(x))
[2021-12-08 02:16:40,058] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/main.py", line 32, in run_get_ads_by_county
[2021-12-08 02:16:40,380] {spark_submit.py:523} INFO - get_daft)(limit, county=county)
[2021-12-08 02:16:40,460] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/scraptools/scrap_main.py", line 252, in get_adds_by_page
[2021-12-08 02:16:40,513] {spark_submit.py:523} INFO - res.append(extract_and_get_data_ads(get_daft, url, county)(daft))
[2021-12-08 02:16:40,724] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/scraptools/scrap_main.py", line 193, in h
[2021-12-08 02:16:40,995] {spark_submit.py:523} INFO - return g(*args)(f(x))
[2021-12-08 02:16:41,145] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/scraptools/scrap_main.py", line 181, in get_data_ads
[2021-12-08 02:16:41,173] {spark_submit.py:523} INFO - res.append(parse_advert_from_daft(ad))
[2021-12-08 02:16:41,238] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/scraptools/scrap_main.py", line 120, in parse_advert
[2021-12-08 02:16:41,257] {spark_submit.py:523} INFO - ad_data = get_ad_data(ad)
[2021-12-08 02:16:41,349] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/fptools/fptools.py", line 184, in format_compose
[2021-12-08 02:16:41,420] {spark_submit.py:523} INFO - vals = [f(x) for f in funcs]
[2021-12-08 02:16:41,526] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/fptools/fptools.py", line 184, in <listcomp>
[2021-12-08 02:16:41,572] {spark_submit.py:523} INFO - vals = [f(x) for f in funcs]
[2021-12-08 02:16:41,651] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/fptools/fptools.py", line 35, in h
[2021-12-08 02:16:41,702] {spark_submit.py:523} INFO - return g(f(x))
[2021-12-08 02:16:41,724] {spark_submit.py:523} INFO - File "/opt/***/jobs/my_packages/scraptools/scrap_info.py", line 37, in extract_id
[2021-12-08 02:16:41,948] {spark_submit.py:523} INFO - return ad.find('p', {'class': re.compile('DaftIDText.')}).get_text()
[2021-12-08 02:16:42,129] {spark_submit.py:523} INFO - AttributeError: 'NoneType' object has no attribute 'find'
[2021-12-08 02:16:58,638] {spark_submit.py:523} INFO - 21/12/08 02:16:54 INFO SparkContext: Invoking stop() from shutdown hook
[2021-12-08 04:23:18,066] {spark_submit.py:523} INFO - 21/12/08 04:20:07 WARN ShutdownHookManager: ShutdownHook '' timeout, java.util.concurrent.TimeoutException
[2021-12-08 04:23:38,452] {spark_submit.py:523} INFO - java.util.concurrent.TimeoutException
[2021-12-08 04:23:38,968] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[2021-12-08 04:23:39,090] {spark_submit.py:523} INFO - at org.apache.hadoop.util.ShutdownHookManager.executeShutdown(ShutdownHookManager.java:124)
[2021-12-08 04:23:40,040] {spark_submit.py:523} INFO - at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:95)
[2021-12-08 04:23:41,539] {spark_submit.py:523} INFO - 21/12/08 04:22:42 WARN QueuedThreadPool: QueuedThreadPool[SparkUI]@1a7a4970{STOPPING,8<=0<=200,i=4,r=-1,q=0}[NO_TRY] Couldn't stop Thread[SparkUI-44,5,main]
[2021-12-08 04:23:50,490] {spark_submit.py:523} INFO - 21/12/08 04:22:42 WARN HeartbeatReceiver: Removing executor 1 with no recent heartbeats: 135929 ms exceeds timeout 120000 ms
[2021-12-08 04:23:55,678] {spark_submit.py:523} INFO - 21/12/08 04:23:42 WARN ShutdownHookManager: ShutdownHook 'ClientFinalizer' timeout, java.util.concurrent.TimeoutException
[2021-12-08 04:23:55,797] {spark_submit.py:523} INFO - java.util.concurrent.TimeoutException
[2021-12-08 04:23:55,821] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[2021-12-08 04:23:55,839] {spark_submit.py:523} INFO - at org.apache.hadoop.util.ShutdownHookManager.executeShutdown(ShutdownHookManager.java:124)
[2021-12-08 04:23:55,889] {spark_submit.py:523} INFO - at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:95)
[2021-12-08 04:23:56,785] {spark_submit.py:523} INFO - 21/12/08 04:23:12 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@94428ae)) by listener AppStatusListener took 160.7611375s.
[2021-12-08 04:24:02,498] {spark_submit.py:523} INFO - 21/12/08 04:23:57 WARN HeartbeatReceiver: Removing executor 0 with no recent heartbeats: 134603 ms exceeds timeout 120000 ms
[2021-12-08 04:24:23,874] {spark_submit.py:523} INFO - 21/12/08 04:24:06 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@94428ae)) by listener SQLAppStatusListener took 6.5169499s.
[2021-12-08 04:24:39,447] {spark_submit.py:523} INFO - 21/12/08 04:24:08 WARN QueuedThreadPool: QueuedThreadPool[SparkUI]@1a7a4970{STOPPING,8<=0<=200,i=4,r=-1,q=0}[NO_TRY] Couldn't stop Thread[SparkUI-42,5,main]
[2021-12-08 04:24:44,991] {spark_submit.py:523} INFO - 21/12/08 04:24:08 WARN NettyRpcEnv: Ignored message: true
[2021-12-08 04:24:45,577] {spark_submit.py:523} INFO - 21/12/08 04:24:24 INFO StandaloneSchedulerBackend: Requesting to kill executor(s) 1
[2021-12-08 04:24:46,704] {spark_submit.py:523} INFO - 21/12/08 04:24:24 WARN NettyRpcEnv: Ignored message: true
[2021-12-08 04:24:47,075] {spark_submit.py:523} INFO - 21/12/08 04:24:24 WARN NettyRpcEnv: Ignored message: true
[2021-12-08 04:24:47,195] {spark_submit.py:523} INFO - 21/12/08 04:24:25 WARN NettyRpcEnv: Ignored message: true
[2021-12-08 04:24:47,363] {spark_submit.py:523} INFO - 21/12/08 04:24:38 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@6ce8bfba)) by listener HeartbeatReceiver took 1.6443722s.
[2021-12-08 04:24:47,665] {spark_submit.py:523} INFO - 21/12/08 04:24:42 WARN QueuedThreadPool: QueuedThreadPool[SparkUI]@1a7a4970{STOPPING,8<=0<=200,i=4,r=-1,q=0}[NO_TRY] Couldn't stop Thread[SparkUI-43,5,main]
[2021-12-08 04:24:47,745] {spark_submit.py:523} INFO - 21/12/08 04:24:45 WARN QueuedThreadPool: QueuedThreadPool[SparkUI]@1a7a4970{STOPPING,8<=0<=200,i=4,r=-1,q=0}[NO_TRY] Couldn't stop Thread[SparkUI-45,5,main]
[2021-12-08 04:24:48,482] {spark_submit.py:523} INFO - 21/12/08 04:24:48 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@23a6c392)) by listener AppStatusListener took 22.9002481s.
[2021-12-08 04:24:57,700] {spark_submit.py:523} INFO - 21/12/08 04:24:55 WARN SparkContext: Ignoring Exception while stopping SparkContext from shutdown hook
[2021-12-08 04:24:58,052] {spark_submit.py:523} INFO - java.lang.InterruptedException
[2021-12-08 04:24:58,463] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1367)
[2021-12-08 04:24:58,557] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
[2021-12-08 04:24:58,581] {spark_submit.py:523} INFO - at org.sparkproject.jetty.server.AbstractConnector.doStop(AbstractConnector.java:371)
[2021-12-08 04:24:58,808] {spark_submit.py:523} INFO - at org.sparkproject.jetty.server.AbstractNetworkConnector.doStop(AbstractNetworkConnector.java:88)
[2021-12-08 04:24:58,842] {spark_submit.py:523} INFO - at org.sparkproject.jetty.server.ServerConnector.doStop(ServerConnector.java:246)
[2021-12-08 04:24:58,948] {spark_submit.py:523} INFO - at org.sparkproject.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
[2021-12-08 04:24:59,304] {spark_submit.py:523} INFO - at org.sparkproject.jetty.server.Server.doStop(Server.java:459)
[2021-12-08 04:24:59,369] {spark_submit.py:523} INFO - at org.sparkproject.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
[2021-12-08 04:24:59,401] {spark_submit.py:523} INFO - at org.apache.spark.ui.ServerInfo.stop(JettyUtils.scala:525)
[2021-12-08 04:24:59,717] {spark_submit.py:523} INFO - at org.apache.spark.ui.WebUI.$anonfun$stop$2(WebUI.scala:174)
[2021-12-08 04:24:59,813] {spark_submit.py:523} INFO - at org.apache.spark.ui.WebUI.$anonfun$stop$2$adapted(WebUI.scala:174)
[2021-12-08 04:24:59,903] {spark_submit.py:523} INFO - at scala.Option.foreach(Option.scala:407)
[2021-12-08 04:25:00,162] {spark_submit.py:523} INFO - at org.apache.spark.ui.WebUI.stop(WebUI.scala:174)
[2021-12-08 04:25:00,199] {spark_submit.py:523} INFO - at org.apache.spark.ui.SparkUI.stop(SparkUI.scala:101)
[2021-12-08 04:25:00,266] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.$anonfun$stop$6(SparkContext.scala:2071)
[2021-12-08 04:25:00,373] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.$anonfun$stop$6$adapted(SparkContext.scala:2071)
[2021-12-08 04:25:00,451] {spark_submit.py:523} INFO - at scala.Option.foreach(Option.scala:407)
[2021-12-08 04:25:00,480] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.$anonfun$stop$5(SparkContext.scala:2071)
[2021-12-08 04:25:00,573] {spark_submit.py:523} INFO - at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1442)
[2021-12-08 04:25:01,888] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.stop(SparkContext.scala:2071)
[2021-12-08 04:25:02,181] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.$anonfun$new$38(SparkContext.scala:667)
[2021-12-08 04:25:02,332] {spark_submit.py:523} INFO - at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214)
[2021-12-08 04:25:02,400] {spark_submit.py:523} INFO - at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188)
[2021-12-08 04:25:03,212] {spark_submit.py:523} INFO - at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2021-12-08 04:25:03,636] {spark_submit.py:523} INFO - at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2019)
[2021-12-08 04:25:03,842] {spark_submit.py:523} INFO - at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188)
[2021-12-08 04:25:03,905] {spark_submit.py:523} INFO - at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2021-12-08 04:25:03,988] {spark_submit.py:523} INFO - at scala.util.Try$.apply(Try.scala:213)
[2021-12-08 04:25:04,025] {spark_submit.py:523} INFO - at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
[2021-12-08 04:25:04,116] {spark_submit.py:523} INFO - at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
[2021-12-08 04:25:04,387] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-08 04:25:04,464] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-08 04:25:04,561] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-08 04:25:04,585] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-08 04:25:04,629] {spark_submit.py:523} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-08 04:25:05,030] {spark_submit.py:523} INFO - 21/12/08 04:24:59 WARN NettyRpcEnv: Ignored message: true
[2021-12-08 04:25:06,305] {spark_submit.py:523} INFO - 21/12/08 04:25:05 INFO DiskBlockManager: Shutdown hook called
[2021-12-08 04:25:21,863] {spark_submit.py:523} INFO - 21/12/08 04:25:21 INFO StandaloneSchedulerBackend: Actual list of executor(s) to be killed is 1
[2021-12-08 04:25:40,469] {spark_submit.py:523} INFO - 21/12/08 04:25:38 ERROR TransportRequestHandler: Error sending result RpcResponse[requestId=7656710617412677831,body=NioManagedBuffer[buf=java.nio.HeapByteBuffer[pos=0 lim=81 cap=156]]] to /172.31.0.5:50216; closing connection
[2021-12-08 04:25:41,018] {spark_submit.py:523} INFO - io.netty.channel.StacklessClosedChannelException
[2021-12-08 04:25:41,098] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
[2021-12-08 04:25:41,281] {spark_submit.py:523} INFO - 21/12/08 04:25:40 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@7743e491)) by listener AppStatusListener took 3.1064338s.
[2021-12-08 04:25:41,374] {spark_submit.py:523} INFO - 21/12/08 04:25:38 ERROR TransportRequestHandler: Error sending result RpcResponse[requestId=8301484464536169785,body=NioManagedBuffer[buf=java.nio.HeapByteBuffer[pos=0 lim=81 cap=156]]] to /172.31.0.6:44988; closing connection
[2021-12-08 04:25:41,427] {spark_submit.py:523} INFO - io.netty.channel.StacklessClosedChannelException
[2021-12-08 04:25:41,452] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
[2021-12-08 04:25:41,596] {spark_submit.py:523} INFO - 21/12/08 04:25:41 INFO ShutdownHookManager: Shutdown hook called
[2021-12-08 04:25:42,931] {spark_submit.py:523} INFO - 21/12/08 04:25:42 INFO ShutdownHookManager: Deleting directory /tmp/spark-2dec4778-7196-409e-b192-35cf29d12235
[2021-12-08 04:25:45,014] {spark_submit.py:523} INFO - 21/12/08 04:25:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-1535437a-ce12-4747-9857-b3c3924de19b
[2021-12-08 04:25:51,093] {spark_submit.py:523} INFO - 21/12/08 04:25:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-1535437a-ce12-4747-9857-b3c3924de19b/userFiles-c841bf51-9eb2-4b95-9293-5acd87ab7ec6
[2021-12-08 04:25:51,206] {spark_submit.py:523} INFO - 21/12/08 04:25:51 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20211208021511-0082/1 is now EXITED (Command exited with code 0)
[2021-12-08 04:25:51,536] {spark_submit.py:523} INFO - 21/12/08 04:25:51 ERROR ShutdownHookManager: ShutdownHookManager shutdown forcefully after 30 seconds.
[2021-12-08 10:07:43,109] {base_job.py:230} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 220, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2171, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2244, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-12-08 10:08:00,639] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2021-12-08 10:07:41,165] {standard_task_runner.py:91} ERROR - Failed to execute job 596 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    self._mask_cmd(spark_submit_cmd), returncode
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py kildare. Error code is: 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1375, in _run_raw_task
    self.refresh_from_db(lock_for_update=True, session=session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 729, in refresh_from_db
    ti: Optional[TaskInstance] = qry.with_for_update().first()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: http://sqlalche.me/e/13/e3q8)
